// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SoftAcademyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void possitiveLogin() {
    // Test name: Possitive Login
    // Step # | name | target | value
    // 1 | open | /login | 
    driver.get("http://poll-app7-20210914.softacad.bg//login");
    // 2 | setWindowSize | 1100x700 | 
    driver.manage().window().setSize(new Dimension(1100, 700));
    // 3 | type | id=usernameOrEmail | normalUser1
    driver.findElement(By.id("usernameOrEmail")).sendKeys("normalUser1");
    // 4 | type | id=password | 123456
    driver.findElement(By.id("password")).sendKeys("123456");
    // 5 | click | name=login | 
    driver.findElement(By.name("login")).click();
    // 6 | click | css=.oi-person | 
    driver.findElement(By.cssSelector(".oi-person")).click();
    // 7 | assertText | id=full-name | NORMAL USER
    assertThat(driver.findElement(By.id("full-name")).getText(), is("NORMAL USER"));
    // 8 | click | name=logout-button | 
    driver.findElement(By.name("logout-button")).click();
  }
  @Test
  public void registratenewuser() {
    // Test name: Registrate new user
    // Step # | name | target | value
    // 1 | setWindowSize | 1100x700 | 
    driver.manage().window().setSize(new Dimension(1100, 700));
    // 2 | open | /signup | 
    driver.get("http://poll-app7-20210914.softacad.bg//signup");
    // 3 | executeScript | return Math.random().toString(36).substring(7); | randomUserName
    vars.put("randomUserName", js.executeScript("return Math.random().toString(36).substring(7);"));
    // 4 | executeScript | return Math.random().toString(36).substring(7); | randomEmail
    vars.put("randomEmail", js.executeScript("return Math.random().toString(36).substring(7);"));
    // 5 | type | id=full-name | ${randomEmail}
    driver.findElement(By.id("full-name")).sendKeys(vars.get("randomEmail").toString());
    // 6 | type | id=username | ${randomUserName}
    driver.findElement(By.id("username")).sendKeys(vars.get("randomUserName").toString());
    // 7 | type | id=email | ${randomEmail}@example.com
    driver.findElement(By.id("email")).sendKeys(vars.get("randomEmail").toString()@example.com);
    // 8 | type | id=password | 654321
    driver.findElement(By.id("password")).sendKeys("654321");
    // 9 | click | id=register | 
    driver.findElement(By.id("register")).click();
    // 10 | type | id=usernameOrEmail | ${randomUserName}
    driver.findElement(By.id("usernameOrEmail")).sendKeys(vars.get("randomUserName").toString());
    // 11 | type | id=password | 654321
    driver.findElement(By.id("password")).sendKeys("654321");
    // 12 | click | name=login | 
    driver.findElement(By.name("login")).click();
    // 13 | click | css=.oi-person | 
    driver.findElement(By.cssSelector(".oi-person")).click();
    // 14 | assertText | id=full-name | ${randomEmail}
    assertThat(driver.findElement(By.id("full-name")).getText(), is("vars.get(\"randomEmail\").toString()"));
  }
  @Test
  public void createpolls() {
    // Test name: Create polls
    // Step # | name | target | value
    // 1 | open | /login | 
    driver.get("http://poll-app7-20210914.softacad.bg//login");
    // 2 | setWindowSize | 1100x700 | 
    driver.manage().window().setSize(new Dimension(1100, 700));
    // 3 | executeScript | return Math.random().toString(36).substring(7); | randomQuestion
    vars.put("randomQuestion", js.executeScript("return Math.random().toString(36).substring(7);"));
    // 4 | executeScript | return Math.random().toString(36).substring(7); | randomAnswear1
    vars.put("randomAnswear1", js.executeScript("return Math.random().toString(36).substring(7);"));
    // 5 | executeScript | return Math.random().toString(36).substring(7); | randomAnswear2
    vars.put("randomAnswear2", js.executeScript("return Math.random().toString(36).substring(7);"));
    // 6 | type | id=usernameOrEmail | tg2admin
    driver.findElement(By.id("usernameOrEmail")).sendKeys("tg2admin");
    // 7 | type | id=password | 123456
    driver.findElement(By.id("password")).sendKeys("123456");
    // 8 | click | name=login | 
    driver.findElement(By.name("login")).click();
    // 9 | click | xpath=//a[contains(@href,'/poll/new')] | 
    driver.findElement(By.xpath("//a[contains(@href,\'/poll/new\')]")).click();
    // 10 | type | xpath=  //textarea[@placeholder='Enter your question'] | ${randomQuestion}
    driver.findElement(By.xpath("  //textarea[@placeholder=\'Enter your question\']")).sendKeys(vars.get("randomQuestion").toString());
    // 11 | type | xpath=//input[@placeholder="Choice 1"] | ${randomAnswear1}
    driver.findElement(By.xpath("//input[@placeholder=\"Choice 1\"]")).sendKeys(vars.get("randomAnswear1").toString());
    // 12 | type | xpath=//input[@placeholder="Choice 2"] | ${randomAnswear2}
    driver.findElement(By.xpath("//input[@placeholder=\"Choice 2\"]")).sendKeys(vars.get("randomAnswear2").toString());
    // 13 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
  }
}
